import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-50 min-h-screen">
        <header className="bg-white shadow p-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold text-blue-700 hover:text-blue-800 transition-colors">
            AI Solution Hub
          </Link>
          <nav className="flex gap-4">
            <Link href="/english-sentence" className="hover:underline">영어 문장 생성</Link>
            <Link href="/celebration-message" className="hover:underline">축하 문구 생성</Link>
          </nav>
        </header>
        <main className="max-w-2xl mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
